import Fluent
import FluentSQL

struct CreateAuthRefreshTokens: AsyncMigration {
    func prepare(on database: any Database) async throws {
        guard let sql = database as? any SQLDatabase else { return }
        try await sql.raw("""
            CREATE TABLE IF NOT EXISTS auth.refresh_tokens (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instance_id uuid,
                token text,
                user_id text,
                revoked boolean,
                created_at timestamptz,
                updated_at timestamptz,
                parent text,
                session_id uuid,
                CONSTRAINT refresh_tokens_token_unique UNIQUE (token),
                CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id) ON DELETE CASCADE
            );
            """).run()
        try await sql.raw("""
            CREATE INDEX IF NOT EXISTS refresh_tokens_parent_idx
                ON auth.refresh_tokens (parent);
            """
        ).run()
        try await sql.raw("""
            CREATE INDEX IF NOT EXISTS refresh_tokens_session_id_revoked_idx
                ON auth.refresh_tokens (session_id, revoked);
            """
        ).run()
        try await sql.raw("""
            CREATE INDEX IF NOT EXISTS refresh_tokens_updated_at_idx
                ON auth.refresh_tokens (updated_at DESC);
            """
        ).run()
    }

    func revert(on database: any Database) async throws {
        guard let sql = database as? any SQLDatabase else { return }
        try await sql.raw("DROP TABLE IF EXISTS auth.refresh_tokens;").run()
    }
}
