import Fluent
import FluentSQL

struct CreateAuthRefreshTokens: AsyncMigration {
    func prepare(on database: any Database) async throws {
        guard let sql = database as? any SQLDatabase else { return }
        try await sql.raw("""
            CREATE TABLE IF NOT EXISTS auth.refresh_tokens (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instance_id uuid,
                token text,
                user_id text,
                revoked boolean,
                created_at timestamptz,
                updated_at timestamptz,
                parent text,
                session_id uuid
            );
            """).run()
    }

    func revert(on database: any Database) async throws {
        guard let sql = database as? any SQLDatabase else { return }
        try await sql.raw("DROP TABLE IF EXISTS auth.refresh_tokens;").run()
    }
}
